---
title: "p8105_hw1_asf2164"
output: html_document
date: "2022-09-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
# install.packages("palmerpenguins")
```



## R Markdown
```{r}
data("penguins", package = "palmerpenguins")
# variables: species, island, bill_length_mm, bill_depth_mm, flipper_lenght_mm, body_mass_mm, body_mass_g, sex, year
summary(penguins)
nrow(penguins) # rows = 344
ncol(penguins) # columns = 8



library(tidyr)
drop_na(penguins, flipper_length_mm)
mean(penguins$flipper_length_mm, na.rm = TRUE) # mean of flipper_length_mm = 200.9152


penguin_plot = ggplot(penguins,
                      aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()

ggsave(
  "penguin_plot.pdf",
  plot = penguin_plot,
  device = NULL,
  path = NULL,
  scale = 1,
  width = NA,
  height = NA,
  dpi = 300,
  limitsize = TRUE,
  bg = NULL,
)

```



## Problem 2 
```{r}
set.seed(3)

problem2plot = tibble(
  normal_var = rnorm(10, mean = 0, sd = 1),
  logical_var = normal_var > 0,
  char_var = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  factor_var = factor(
    c(
      "small",
      "medium",
      "large",
      "large",
      "large",
      "medium",
      "medium",
      "small",
      "large",
      "small"
    )
  )
)

mean(pull(problem2plot, var = normal_var)) #mean = -0.06713568
mean(pull(problem2plot, var = logical_var)) #mean = 0.6
mean(pull(problem2plot, var = char_var)) #mean = N/A, this argument is not numerical or logical
mean(pull(problem2plot, var = factor_var)) #mean = N/A, this argument is not numerical or logical

as.numeric(problem2plot$normal_var) #[1] -0.96193342 -0.29252572  0.25878822 -1.15213189  0.19578283  0.03012394  0.08541773  1.11661021 -1.21885742 [10]  1.26736872
as.numeric(problem2plot$logical_var) # [1] 0 0 1 0 1 1 1 1 0 1
as.numeric(problem2plot$char_var) #[1] NA NA NA NA NA NA NA NA NA NA, gives warning that N/As were introduced by coercion, this variable cannot produce a numeric value as a character variable 
as.numeric(problem2plot$factor_var) #[1] 3 2 1 1 1 2 2 3 1 3
```

